---
title: jekyllDecent
timezone: America/Guyana
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
subtitle: Example Blog
description: This is the jekyllTheme example blog. It only exists to demonstrate how
  the theme looks and feels.
keywords: demo theme example github jekyll features
language: es
baseurl: 
url: http://jwillmer.github.io/jekyllDecent
permalink: "/blog/:categories/:title"
cover: "/assets/mountain-cover.jpg"
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
include:
- _pages
exclude:
- vendor
gems:
- jekyll-mentions
- jekyll-feed
- jekyll-sitemap
- jekyll-redirect-from
